### ISSUE TITLE
DNF Times

### ISSUE THREAD

**Issue by GBratsos** [enamelizer/DR2Rallymaster#4]
Hello,

I would like a feature request if is possible. I saw that on the results of the drivers that DNF we don't get their times on stages and overall.

Is there a way to also have their times and not just a DNF ?

I want to simulate the RALLY 2 regulations on my rallies so i need to have the times of the drivers on all stages even from those who are DNF.

**Comment by enamelizer** [comment]
The way it works now it is that there should only be a DNF instead of a time when the "default stage time" is detected. That is 8 min on short stages and 15 min on long stages. The driver would no longer be able to continue, so rest of the rally would then either have 8 / 15 min stage times or no times at all for that driver.

There is an exploit where a driver can Alt+F4 right after a DNF and be able to continue driving the rally, this is the only way they would have non-default stage times (this is what the DNF system was designed to catch).

I should be able to output the raw data from the Racenet API without the DNF processing, I will take a look at this but it may be a few weeks before I have a chance to look at it.

**Comment by GBratsos** [comment]
As i understood the DNF system will give the 8/15 min stage time on every stage after the DNF.
That's too bad because it doesn't simulate the real rallies.

I think that we should have the time of every stage if is that possible with or without the 8/15 min stage time i'm ok with that.
