### ISSUE TITLE
Export missing a lot of data

### ISSUE THREAD

**Issue by JBrame** [enamelizer/DR2Rallymaster#6]
The export seems to be missing a lot of data. In the club the stages all have times, but the export has DNFs for most of the people:
![image](https://user-images.githubusercontent.com/6168847/105706222-2f6dc700-5f09-11eb-946d-fa45c36635a2.png)
![image](https://user-images.githubusercontent.com/6168847/105706273-3eed1000-5f09-11eb-8456-b5a52a323593.png)

**Comment by enamelizer** [comment]
This happens when Racenet returns incomplete stage data. When Racenet is having issues you can see incomplete data sets on the clubs site as well but it is more obvious with the rallymaster tool. The system will try to capture all drivers in the rally, so all drivers will be listed on each stage even if they do not have have a stage time.

Give it another run and if you are still having issues let me know what the club ID / championship / rally is and I will take a look.
